# Generated by Django 5.0.7 on 2024-09-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_close_reason_lead_database_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='mobile_number',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='through',
        ),
        migrations.AlterField(
            model_name='lead',
            name='database',
            field=models.CharField(default='Not Specified', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='interested_in',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_whatsapp_blast',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
