# Generated by Django 5.0.7 on 2024-10-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='call_made',
            field=models.BooleanField(default=False),
        ),
    ]
