# Generated by Django 5.0.7 on 2024-10-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_call_made'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='followup_of_last_call',
            field=models.DateField(blank=True, null=True),
        ),
    ]
