# Generated by Django 5.0.7 on 2024-10-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_lead_followup_of_last_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='interested',
            field=models.BooleanField(default=False),
        ),
    ]
